# Generated by Django 2.2.28 on 2022-10-08 08:40

from django.db import migrations


def copy_flatownwers_to_owners_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flatownwers_to_owners_model)
    ]
