# Generated by Django 2.2.28 on 2022-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221008_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='owns', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
    ]
