# Generated by Django 2.2.28 on 2022-10-09 12:28

from django.db import migrations

def add_own_flat_to_flats_field(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        owner.flats.set(Flat.objects.filter(owner=owner.owner))
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20221009_1507'),
    ]

    operations = [
        migrations.RunPython(add_own_flat_to_flats_field)
    ]
